# Learn more about configuring your Shopify app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "echoSignal"
client_id = "your_client_id_here"
application_url = "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev"
embedded = true

[access_scopes]
# Use HTTPS URLs to ensure secure data transmission
scopes = "read_orders,read_products,read_customers,read_analytics,read_inventory,read_reports"

[auth]
redirect_urls = [
  "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/auth/shopify/callback",
  "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/auth/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["orders/create", "orders/updated", "orders/paid", "orders/cancelled"]
uri = "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/api/webhooks/orders"

[[webhooks.subscriptions]]
topics = ["customers/create", "customers/update"]
uri = "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/api/webhooks/customers"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update"]
uri = "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/api/webhooks/products"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://3ymihe3bzzhzubxr-7yexf06k8.preview.co.dev/api/webhooks/app/uninstalled"

[pos]
embedded = false